# Generated by Django 6.0 on 2026-03-05 05:20

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_code', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['county_name'], name='county_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='records.county')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='records.person')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='records.person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name', 'middle_name', 'sex'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('marriage_record_image', models.ImageField(blank=True, null=True, upload_to='marriage_records/')),
                ('marriage_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.city')),
                ('marriage_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.county')),
                ('spouse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse1', to='records.person')),
                ('spouse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse2', to='records.person')),
            ],
            options={
                'verbose_name': 'Marriage',
                'verbose_name_plural': 'Marriages',
                'ordering': ['marriage_date', 'marriage_county'],
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('death_record_image', models.ImageField(blank=True, null=True, upload_to='death_records/')),
                ('death_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.city')),
                ('death_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.county')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death', to='records.person')),
            ],
            options={
                'verbose_name': 'Death',
                'verbose_name_plural': 'Deaths',
                'ordering': ['death_date', 'death_county'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=2000)),
                ('creation_time', models.DateTimeField()),
                ('commenter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('commenter_email', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.person')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_record_image', models.ImageField(blank=True, null=True, upload_to='birth_records/')),
                ('birth_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.city')),
                ('birth_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.county')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='records.person')),
            ],
            options={
                'verbose_name': 'Birth',
                'verbose_name_plural': 'Births',
                'ordering': ['birth_date', 'birth_county'],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['city_name'], name='city_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='person_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='person_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['middle_name'], name='person_middle_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(fields=('spouse1', 'spouse2', 'marriage_date'), name='unique_marriages'),
        ),
    ]
