# Generated by Django 6.0 on 2026-03-13 04:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_birth_death_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriage',
            old_name='death_record_image',
            new_name='marriage_record_image',
        ),
        migrations.AddField(
            model_name='birth',
            name='birth_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='person',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='records.person'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='death',
            name='death_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='death',
            name='death_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='person',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='death', to='records.person'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='marriage',
            name='marriage_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1, null=True),
        ),
    ]
